apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot-backend-svc
  namespace: production
spec:
  selector:
    app: rag-chatbot-backend
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot-frontend-svc
  namespace: production
spec:
  selector:
    app: rag-chatbot-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
